# Site settings
title: "Saikrishnan Murali Portfolio"
description: "Lead and Analyst with over 5 Years of Work Experience and a Masters in Data Analytics. Eligible to work in Ireland without sponsorship."

# Build settings
markdown: kramdown
theme: minima

# Permalinks
permalink: pretty

# GitHub Pages settings
remote_theme: minima

# Exclude files/folders from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
nav_links:
  - title: "My Projects"
    url: "index.html"
    active: true
